export interface DirectoryTool {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: string;
  pricing: "free" | "freemium" | "paid" | "open-source" | "enterprise";
  pricingLabel: string;
  tags: string[];
  href: string;
  badge?: string;
  featured?: boolean;
}

export const directoryTools: DirectoryTool[] = [
  // ── LLM / Chat ──
  { id: "chatgpt", name: "ChatGPT", tagline: "Most popular AI assistant", description: "OpenAI's conversational AI — handles writing, coding, analysis, image generation, and more. The most widely used AI tool globally.", category: "LLM / Chat", pricing: "freemium", pricingLabel: "Free · Plus $20/mo", tags: ["chat", "writing", "coding", "images"], href: "https://chat.openai.com", featured: true, badge: "Most Popular" },
  { id: "claude", name: "Claude", tagline: "Best for writing and reasoning", description: "Anthropic's AI assistant — best-in-class writing quality, 200K context window, and strong analytical reasoning. Preferred by professionals.", category: "LLM / Chat", pricing: "freemium", pricingLabel: "Free · Pro $20/mo", tags: ["chat", "writing", "analysis", "coding"], href: "https://claude.ai", featured: true, badge: "Best Writing" },
  { id: "gemini", name: "Gemini", tagline: "Google's multimodal AI assistant", description: "Google's AI assistant with native Google Workspace integration, 1M+ token context, and real-time Google Search grounding.", category: "LLM / Chat", pricing: "freemium", pricingLabel: "Free · Advanced $20/mo", tags: ["chat", "google", "multimodal", "search"], href: "https://gemini.google.com", featured: true },
  { id: "perplexity", name: "Perplexity AI", tagline: "AI search engine with real citations", description: "Research-focused AI that provides real-time web answers with verifiable citations. The most trustworthy AI for fact-finding.", category: "LLM / Chat", pricing: "freemium", pricingLabel: "Free · Pro $20/mo", tags: ["search", "research", "citations", "real-time"], href: "https://perplexity.ai", featured: true, badge: "Best for Research" },
  { id: "deepseek", name: "DeepSeek", tagline: "Best value AI — fraction of the cost", description: "Chinese open-source AI with benchmark performance rivaling GPT-4o at a fraction of the API cost. Best budget LLM option.", category: "LLM / Chat", pricing: "freemium", pricingLabel: "Free · API from $0.14/M tokens", tags: ["chat", "api", "open-source", "budget"], href: "https://chat.deepseek.com", badge: "Best Value" },
  { id: "mistral", name: "Mistral AI", tagline: "Best European privacy-first AI", description: "French AI company offering open and closed models with GDPR compliance, strong multilingual capabilities, and competitive pricing.", category: "LLM / Chat", pricing: "freemium", pricingLabel: "Free · API from $2/M tokens", tags: ["chat", "european", "privacy", "multilingual"], href: "https://mistral.ai" },
  { id: "grok", name: "Grok (xAI)", tagline: "Real-time X/Twitter integrated AI", description: "xAI's AI assistant with real-time access to X (Twitter) data. Unique for current events and social media intelligence.", category: "LLM / Chat", pricing: "paid", pricingLabel: "X Premium $8/mo", tags: ["chat", "real-time", "social-media"], href: "https://grok.com" },
  { id: "copilot-ms", name: "Microsoft Copilot", tagline: "AI assistant built into Microsoft 365", description: "GPT-4o powered AI assistant embedded in Word, Excel, PowerPoint, Teams, and Outlook. Best for enterprise Microsoft users.", category: "LLM / Chat", pricing: "freemium", pricingLabel: "Free · M365 Copilot $30/user/mo", tags: ["productivity", "microsoft", "office", "enterprise"], href: "https://copilot.microsoft.com" },

  // ── Coding Tools ──
  { id: "github-copilot", name: "GitHub Copilot", tagline: "Best IDE coding assistant", description: "Microsoft's AI coding assistant with native VS Code and JetBrains integration. Best for inline autocomplete and everyday coding.", category: "Coding", pricing: "paid", pricingLabel: "$10/mo individual · $19/user/mo business", tags: ["coding", "autocomplete", "vscode", "ide"], href: "https://github.com/features/copilot", featured: true, badge: "Most Popular" },
  { id: "cursor", name: "Cursor", tagline: "Best AI-native code editor", description: "VS Code fork rebuilt around AI — codebase-wide context, Composer mode for multi-file edits, works with Claude and GPT-4o.", category: "Coding", pricing: "freemium", pricingLabel: "Free · Pro $20/mo", tags: ["coding", "editor", "vscode", "codebase"], href: "https://cursor.sh", featured: true, badge: "Best Editor" },
  { id: "claude-code", name: "Claude Code", tagline: "Most powerful coding agent", description: "Anthropic's terminal-based AI coding agent — best for complex refactors, large codebase changes, and senior engineering tasks.", category: "Coding", pricing: "paid", pricingLabel: "API-based, ~$20-100+/mo", tags: ["coding", "terminal", "agent", "refactoring"], href: "https://docs.anthropic.com/claude-code", badge: "Most Powerful" },
  { id: "windsurf", name: "Windsurf", tagline: "Best value AI code editor", description: "Codeium's AI-native editor — Cursor alternative at lower price. Cascade AI for codebase-wide context.", category: "Coding", pricing: "freemium", pricingLabel: "Free · Pro $15/mo", tags: ["coding", "editor", "vscode", "budget"], href: "https://windsurf.ai", badge: "Best Value" },
  { id: "tabnine", name: "Tabnine", tagline: "Best private/on-premise coding AI", description: "AI code completion that can run fully on-premise. Best for enterprises with strict IP and data security requirements.", category: "Coding", pricing: "freemium", pricingLabel: "Free · Pro $12/mo · Enterprise custom", tags: ["coding", "privacy", "enterprise", "on-premise"], href: "https://tabnine.com" },
  { id: "cody", name: "Cody (Sourcegraph)", tagline: "Best for large multi-repo codebases", description: "Sourcegraph's AI coding assistant that indexes your entire enterprise codebase across repositories for comprehensive context.", category: "Coding", pricing: "freemium", pricingLabel: "Free · Enterprise custom", tags: ["coding", "enterprise", "codebase", "search"], href: "https://sourcegraph.com/cody" },

  // ── Image Generation ──
  { id: "midjourney", name: "Midjourney", tagline: "Best image quality available", description: "The gold standard for AI art generation. Unmatched aesthetic quality, lighting, and composition. Discord-based interface.", category: "Image Generation", pricing: "paid", pricingLabel: "Basic $10/mo · Standard $30/mo", tags: ["image", "art", "creative", "discord"], href: "https://midjourney.com", featured: true, badge: "Best Quality" },
  { id: "dalle3", name: "DALL-E 3", tagline: "Best prompt accuracy for images", description: "OpenAI's image generator — best at following complex prompts and including accurate text in images. Built into ChatGPT.", category: "Image Generation", pricing: "freemium", pricingLabel: "ChatGPT Plus $20/mo · API $0.04/image", tags: ["image", "openai", "text-in-image"], href: "https://openai.com/dall-e-3" },
  { id: "stable-diffusion", name: "Stable Diffusion", tagline: "Best free open-source image generator", description: "Open-source image generation model. Run locally for free, unlimited generations, full commercial rights. Requires GPU setup.", category: "Image Generation", pricing: "open-source", pricingLabel: "Free (self-hosted)", tags: ["image", "open-source", "local", "free"], href: "https://stability.ai", badge: "Open Source" },
  { id: "ideogram", name: "Ideogram", tagline: "Best for text in AI images", description: "AI image generator excelling at typography and text rendering — best for logos, social graphics, and designs with text.", category: "Image Generation", pricing: "freemium", pricingLabel: "Free (10/day) · Basic $8/mo", tags: ["image", "text", "logos", "design"], href: "https://ideogram.ai" },
  { id: "adobe-firefly", name: "Adobe Firefly", tagline: "Best commercially safe AI images", description: "Adobe's AI generator trained exclusively on licensed content — fully safe for commercial use with no copyright concerns.", category: "Image Generation", pricing: "freemium", pricingLabel: "Free (25/mo) · Creative Cloud plans", tags: ["image", "commercial", "adobe", "safe"], href: "https://firefly.adobe.com" },
  { id: "flux", name: "Flux (Black Forest Labs)", tagline: "Best new AI image model", description: "State-of-the-art image generation model from former Stable Diffusion team. Photorealistic quality competitive with Midjourney.", category: "Image Generation", pricing: "paid", pricingLabel: "via Replicate from $0.003/image", tags: ["image", "photorealistic", "api"], href: "https://blackforestlabs.ai" },

  // ── Video Generation ──
  { id: "sora", name: "Sora (OpenAI)", tagline: "Best overall AI video quality", description: "OpenAI's text-to-video model. Most physically realistic AI video, up to 20 seconds at 1080p. Included with ChatGPT Pro.", category: "Video Generation", pricing: "paid", pricingLabel: "ChatGPT Pro $200/mo", tags: ["video", "text-to-video", "cinematic"], href: "https://sora.com", featured: true, badge: "Best Quality" },
  { id: "runway", name: "Runway Gen-3", tagline: "Best for creative video production", description: "Industry-standard AI video tool for professionals. Advanced camera controls, motion brush, and video-to-video editing.", category: "Video Generation", pricing: "paid", pricingLabel: "Standard $15/mo · Pro $35/mo", tags: ["video", "creative", "professional", "vfx"], href: "https://runwayml.com", featured: true },
  { id: "pika", name: "Pika", tagline: "Best value AI video generator", description: "Fast, accessible AI video generation. Best for social media clips, quick marketing content, and beginner video creators.", category: "Video Generation", pricing: "freemium", pricingLabel: "Free · Basic $8/mo", tags: ["video", "social-media", "fast", "beginner"], href: "https://pika.style/?via=wecompareai", badge: "Best Value" },
  { id: "kling", name: "Kling AI", tagline: "Best Chinese AI video alternative", description: "Kuaishou's AI video generator with excellent quality at competitive pricing. Strong for longer video clips.", category: "Video Generation", pricing: "freemium", pricingLabel: "Free tier available", tags: ["video", "budget", "long-form"], href: "https://klingai.com" },

  // ── Audio / Voice ──
  { id: "elevenlabs", name: "ElevenLabs", tagline: "Best voice cloning quality", description: "Best-in-class AI voice cloning and text-to-speech. 29 languages, real-time voice changing, professional grade output.", category: "Audio / Voice", pricing: "freemium", pricingLabel: "Free · Starter $5/mo · Creator $22/mo", tags: ["voice", "tts", "cloning", "audio"], href: "https://try.elevenlabs.io/wecompareai", featured: true, badge: "Best Quality" },
  { id: "openai-tts", name: "OpenAI TTS", tagline: "Best value TTS API", description: "OpenAI's text-to-speech API — extremely natural voices, competitive pricing, reliable infrastructure. 6 voice options.", category: "Audio / Voice", pricing: "paid", pricingLabel: "$15/M characters", tags: ["tts", "api", "voice", "budget"], href: "https://platform.openai.com/docs/guides/text-to-speech" },
  { id: "murf", name: "Murf AI", tagline: "Best studio voiceover tool", description: "Professional voiceover platform with built-in video editor. 120+ voices, emphasis controls, team collaboration.", category: "Audio / Voice", pricing: "freemium", pricingLabel: "Free · Basic $29/mo · Pro $39/mo", tags: ["voiceover", "studio", "video", "team"], href: "https://murf.ai" },
  { id: "playht", name: "Play.ht", tagline: "Best TTS API for developers", description: "Developer-focused TTS with streaming API, ultra-realistic voice cloning, and gRPC support for low-latency applications.", category: "Audio / Voice", pricing: "paid", pricingLabel: "Creator $39/mo · Starter $99/mo", tags: ["tts", "api", "streaming", "developers"], href: "https://play.ht" },

  // ── Music Generation ──
  { id: "suno", name: "Suno", tagline: "Best AI music generator", description: "Generate complete songs with lyrics and vocals from a text prompt. Best overall quality and genre range.", category: "Music Generation", pricing: "freemium", pricingLabel: "Free · Pro $10/mo · Premier $30/mo", tags: ["music", "songs", "vocals", "lyrics"], href: "https://suno.com", featured: true, badge: "Best Overall" },
  { id: "udio", name: "Udio", tagline: "Most creative AI music tool", description: "Genre-blending AI music generator. Best for experimental sounds and unique musical combinations.", category: "Music Generation", pricing: "freemium", pricingLabel: "Free · Standard $10/mo", tags: ["music", "experimental", "creative"], href: "https://udio.com" },
  { id: "stable-audio", name: "Stable Audio", tagline: "Best for instrumental/background music", description: "Stability AI's music generator — purpose-built for instrumental, loopable background tracks for video and apps.", category: "Music Generation", pricing: "freemium", pricingLabel: "Free · Membership $12/mo", tags: ["music", "instrumental", "background", "open-source"], href: "https://stableaudio.com" },

  // ── Writing & Content ──
  { id: "jasper", name: "Jasper AI", tagline: "Best enterprise AI writing platform", description: "Marketing-focused AI writing tool with brand voice training, campaign management, and team workflows.", category: "Writing & Content", pricing: "paid", pricingLabel: "Creator $49/mo · Pro $69/mo", tags: ["writing", "marketing", "brand", "team"], href: "https://jasper.ai" },
  { id: "copy-ai", name: "Copy.ai", tagline: "Best for sales and marketing copy", description: "AI copywriting tool optimized for ads, emails, landing pages, and sales sequences. GTM automation features.", category: "Writing & Content", pricing: "freemium", pricingLabel: "Free · Starter $49/mo", tags: ["writing", "copywriting", "sales", "marketing"], href: "https://copy.ai" },
  { id: "grammarly", name: "Grammarly", tagline: "Best AI writing assistant for editing", description: "AI writing tool focused on grammar, clarity, tone, and plagiarism detection. Works across all web apps.", category: "Writing & Content", pricing: "freemium", pricingLabel: "Free · Premium $12/mo", tags: ["writing", "editing", "grammar", "clarity"], href: "https://grammarly.com", badge: "Most Used" },
  { id: "notion-ai", name: "Notion AI", tagline: "Best AI for knowledge management", description: "AI embedded in Notion — summarize notes, generate content, and query your entire workspace knowledge base.", category: "Writing & Content", pricing: "paid", pricingLabel: "$10/user/mo (add-on)", tags: ["writing", "notes", "productivity", "knowledge"], href: "https://notion.so/ai" },

  // ── Research & Search ──
  { id: "elicit", name: "Elicit", tagline: "Best AI for academic research", description: "AI research assistant for systematic literature reviews. Searches academic papers and extracts findings at scale.", category: "Research & Search", pricing: "freemium", pricingLabel: "Free · Plus $12/mo · Pro $48/mo", tags: ["research", "academic", "papers", "literature"], href: "https://elicit.com", badge: "Best for Academia" },
  { id: "consensus", name: "Consensus", tagline: "Best for scientific consensus search", description: "Search engine for scientific papers — finds what the research actually says on any topic with consensus indicators.", category: "Research & Search", pricing: "freemium", pricingLabel: "Free · Premium $11/mo", tags: ["research", "science", "papers", "consensus"], href: "https://consensus.app" },
  { id: "youcom", name: "You.com", tagline: "Best free AI search engine", description: "Privacy-focused AI search with citations. Free unlimited searches, code mode for developers, and no ad tracking.", category: "Research & Search", pricing: "freemium", pricingLabel: "Free · Pro $20/mo", tags: ["search", "research", "privacy", "citations"], href: "https://you.com" },

  // ── Productivity ──
  { id: "reclaim", name: "Reclaim AI", tagline: "Best AI calendar manager", description: "AI that automatically schedules tasks, protects focus time, and optimizes your Google Calendar around priorities.", category: "Productivity", pricing: "freemium", pricingLabel: "Free · Starter $10/mo", tags: ["calendar", "productivity", "scheduling", "focus"], href: "https://reclaim.ai" },
  { id: "otter", name: "Otter.ai", tagline: "Best AI meeting notes", description: "Real-time meeting transcription, AI summaries, and action items. Integrates with Zoom, Teams, and Google Meet.", category: "Productivity", pricing: "freemium", pricingLabel: "Free · Pro $17/mo", tags: ["meetings", "transcription", "notes", "productivity"], href: "https://otter.ai", badge: "Best for Meetings" },
  { id: "mem", name: "Mem AI", tagline: "Best AI-powered note taking", description: "Self-organizing note-taking app with AI that automatically connects related ideas and resurfaces relevant notes.", category: "Productivity", pricing: "paid", pricingLabel: "Pro $14.99/mo", tags: ["notes", "knowledge", "productivity", "pkm"], href: "https://mem.ai" },

  // ── Automation ──
  { id: "make", name: "Make.com", tagline: "Best no-code AI automation", description: "Connect AI models to 2,000+ apps without code. Automate workflows connecting Claude, ChatGPT to your business stack.", category: "Automation", pricing: "freemium", pricingLabel: "Free · Core $9/mo · Pro $16/mo", tags: ["automation", "no-code", "workflows", "integration"], href: "https://www.make.com/en/register?pc=wecompareai", featured: true, badge: "Best Automation" },
  { id: "zapier", name: "Zapier AI", tagline: "Largest automation ecosystem", description: "Connect 7,000+ apps with AI-powered automation. Largest integration library. AI features for natural language automation.", category: "Automation", pricing: "freemium", pricingLabel: "Free · Starter $29/mo", tags: ["automation", "no-code", "integration", "workflows"], href: "https://zapier.com" },
  { id: "n8n", name: "n8n", tagline: "Best open-source automation platform", description: "Self-hostable workflow automation with AI nodes. Open-source alternative to Zapier with full data control.", category: "Automation", pricing: "open-source", pricingLabel: "Free (self-hosted) · Cloud $24/mo", tags: ["automation", "open-source", "self-hosted", "workflows"], href: "https://n8n.io" },

  // ── Customer Support ──
  { id: "intercom-fin", name: "Intercom Fin", tagline: "Best AI customer support agent", description: "GPT-4o powered support agent resolving ~50% of tickets autonomously. Seamless human handoff with full context.", category: "Customer Support", pricing: "paid", pricingLabel: "From $74/mo + $0.99/resolved conversation", tags: ["support", "chatbot", "saas", "ai-agent"], href: "https://intercom.com", badge: "Best Resolution Rate" },
  { id: "tidio", name: "Tidio", tagline: "Best AI support for small businesses", description: "Lyro AI chatbot for SMBs — easy setup, Shopify integration, handles FAQ deflection automatically.", category: "Customer Support", pricing: "freemium", pricingLabel: "Free · Starter $29/mo", tags: ["support", "chatbot", "shopify", "smb"], href: "https://tidio.com" },
  { id: "intercom", name: "Zendesk AI", tagline: "Best enterprise support platform", description: "Enterprise support with AI triage, agent assist, and analytics. Handles high-volume operations with SLA management.", category: "Customer Support", pricing: "paid", pricingLabel: "Suite from $69/agent/mo", tags: ["support", "enterprise", "ticketing", "analytics"], href: "https://zendesk.com" },

  // ── Design & Creative ──
  { id: "canva-ai", name: "Canva AI", tagline: "Best AI for non-designers", description: "Magic Studio AI features in Canva — generate images, remove backgrounds, resize designs, and create presentations with AI.", category: "Design & Creative", pricing: "freemium", pricingLabel: "Free · Pro $14.99/mo", tags: ["design", "presentation", "images", "no-code"], href: "https://canva.com", badge: "Most Accessible" },
  { id: "figma-ai", name: "Figma AI", tagline: "Best AI for UX/UI designers", description: "AI features in Figma — generate UI, auto-layout, first drafts from prompts, and design iteration assistance.", category: "Design & Creative", pricing: "freemium", pricingLabel: "Free · Professional $12/mo", tags: ["design", "ui", "ux", "figma"], href: "https://figma.com" },
  { id: "framer-ai", name: "Framer AI", tagline: "Best for AI website generation", description: "Generate entire websites from text descriptions. AI-powered web builder with professional templates.", category: "Design & Creative", pricing: "freemium", pricingLabel: "Free · Mini $5/mo · Basic $15/mo", tags: ["website", "design", "no-code", "ai-generated"], href: "https://framer.com" },

  // ── Developer Tools ──
  { id: "openai-api", name: "OpenAI API", tagline: "Most popular AI API", description: "GPT-4o, o1, and DALL-E via API. Largest ecosystem, most documentation, and widest third-party support.", category: "Developer Tools", pricing: "paid", pricingLabel: "Pay-per-use from $0.15/M tokens", tags: ["api", "developers", "gpt-4o", "ecosystem"], href: "https://platform.openai.com", badge: "Most Popular" },
  { id: "anthropic-api", name: "Anthropic API", tagline: "Best API for quality-focused builders", description: "Claude API — best reasoning quality, 200K context, Constitutional AI safety. Growing developer ecosystem.", category: "Developer Tools", pricing: "paid", pricingLabel: "Pay-per-use from $3/M tokens", tags: ["api", "developers", "claude", "quality"], href: "https://anthropic.com/api" },
  { id: "groq", name: "Groq", tagline: "Fastest AI inference available", description: "LPU-based inference platform — runs open-source models (LLaMA, Mixtral) at 10x the speed of GPU inference.", category: "Developer Tools", pricing: "freemium", pricingLabel: "Free tier · Pay-per-use", tags: ["api", "speed", "inference", "llama"], href: "https://groq.com", badge: "Fastest" },
  { id: "vercel-ai", name: "Vercel AI SDK", tagline: "Best SDK for building AI web apps", description: "TypeScript SDK for building AI-powered web applications. Works with any LLM, streaming built-in, React hooks.", category: "Developer Tools", pricing: "open-source", pricingLabel: "Free (open source)", tags: ["sdk", "nextjs", "typescript", "react"], href: "https://sdk.vercel.ai" },

  // ── Business Intelligence ──
  { id: "tableau-ai", name: "Tableau AI (Salesforce)", tagline: "Best AI for data visualization", description: "Einstein AI in Tableau — natural language queries on your data, automated insights, and predictive forecasting.", category: "Business Intelligence", pricing: "paid", pricingLabel: "Tableau from $75/user/mo", tags: ["analytics", "visualization", "bi", "enterprise"], href: "https://tableau.com" },
  { id: "power-bi-copilot", name: "Power BI Copilot", tagline: "Best AI BI for Microsoft users", description: "Microsoft's AI in Power BI — generate reports, write DAX formulas, and get natural language data summaries.", category: "Business Intelligence", pricing: "paid", pricingLabel: "Power BI Pro $10/user/mo", tags: ["analytics", "bi", "microsoft", "reporting"], href: "https://powerbi.microsoft.com" },
];

export const DIRECTORY_CATEGORIES = [...new Set(directoryTools.map((t) => t.category))];

export const PRICING_FILTERS = [
  { value: "all", label: "All Pricing" },
  { value: "free", label: "Free" },
  { value: "freemium", label: "Freemium" },
  { value: "open-source", label: "Open Source" },
  { value: "paid", label: "Paid" },
  { value: "enterprise", label: "Enterprise" },
] as const;

export function getFeaturedTools(): DirectoryTool[] {
  return directoryTools.filter((t) => t.featured);
}
