export interface GlossaryTerm {
  term: string;
  slug: string;
  category: string;
  definition: string;
  expanded: string;
  example?: string;
  relatedTerms: string[];
  lastUpdated: string;
}

export const glossaryTerms: GlossaryTerm[] = [
  // ── Core Concepts ──
  { term: "Large Language Model (LLM)", slug: "llm", category: "Core Concepts", definition: "A type of AI model trained on vast amounts of text data that can generate, summarize, translate, and reason about language.", expanded: "LLMs are neural networks with billions of parameters, trained using self-supervised learning on internet-scale text. They predict the next token in a sequence, which — at sufficient scale — produces models capable of complex reasoning, coding, writing, and conversation. Examples include GPT-4o, Claude, Gemini, and LLaMA.", example: "GPT-4o, Claude Opus 4, and Gemini 2.5 Pro are all large language models.", relatedTerms: ["token", "transformer", "fine-tuning", "foundation-model"], lastUpdated: "2026-04-11" },
  { term: "Token", slug: "token", category: "Core Concepts", definition: "The basic unit of text that AI language models process — roughly equivalent to 3/4 of a word in English.", expanded: "Tokenization breaks text into smaller pieces (tokens) before an LLM processes it. One token is approximately 4 characters or 0.75 words in English. '1 million tokens' is roughly 750,000 words or about 1,500 pages. API pricing is measured per token — knowing token counts helps estimate costs.", example: "The sentence 'Hello, how are you?' is approximately 6 tokens.", relatedTerms: ["context-window", "tokenization", "llm"], lastUpdated: "2026-04-11" },
  { term: "Context Window", slug: "context-window", category: "Core Concepts", definition: "The maximum amount of text (measured in tokens) that an AI model can 'see' and process in a single interaction.", expanded: "Think of the context window as the AI's working memory. Everything inside the context window — your conversation history, instructions, documents you've shared — is available to the model. Text outside the window is forgotten. Larger context windows allow processing entire books, codebases, or lengthy documents in one prompt. Claude has 200K tokens, Gemini up to 2M.", example: "Claude's 200K context window can hold roughly 150,000 words — about the length of a full novel.", relatedTerms: ["token", "llm", "rag"], lastUpdated: "2026-04-11" },
  { term: "Hallucination", slug: "hallucination", category: "Core Concepts", definition: "When an AI model generates confident-sounding but factually incorrect or fabricated information.", expanded: "Hallucination is one of the biggest challenges with LLMs. Models are trained to produce plausible-sounding text, not necessarily true text. They can invent citations, facts, statistics, and even entire papers that don't exist — stated with complete confidence. Mitigation strategies include RAG (grounding in real documents), web search integration, and using models with knowledge cutoffs close to the present.", example: "An LLM might confidently cite a scientific paper that doesn't exist, with a real-sounding author and journal name.", relatedTerms: ["rag", "grounding", "benchmark"], lastUpdated: "2026-04-11" },
  { term: "Prompt Engineering", slug: "prompt-engineering", category: "Core Concepts", definition: "The practice of crafting inputs to AI models to reliably get better, more accurate, or more specific outputs.", expanded: "Prompt engineering includes techniques like chain-of-thought (asking the model to reason step by step), few-shot prompting (giving examples), role assignment, and structured output formatting. A well-engineered prompt can dramatically improve output quality without changing the underlying model.", example: "Adding 'Let's think step by step' to a math problem prompt significantly improves LLM accuracy.", relatedTerms: ["few-shot", "chain-of-thought", "system-prompt"], lastUpdated: "2026-04-11" },
  { term: "Transformer", slug: "transformer", category: "Architecture", definition: "The neural network architecture that underpins all modern large language models, introduced by Google in 2017.", expanded: "The Transformer architecture, introduced in the paper 'Attention Is All You Need' (Vaswani et al., 2017), replaced previous recurrent neural networks with a self-attention mechanism that processes all tokens in parallel. This enabled training on much larger datasets with greater efficiency. Every major LLM (GPT, Claude, Gemini, LLaMA) is based on the Transformer architecture.", example: "GPT stands for Generative Pre-trained Transformer — named after the architecture it uses.", relatedTerms: ["attention-mechanism", "llm", "foundation-model"], lastUpdated: "2026-04-11" },
  { term: "Attention Mechanism", slug: "attention-mechanism", category: "Architecture", definition: "The core innovation in Transformer models that allows AI to weigh the importance of different parts of input text when generating each output token.", expanded: "Self-attention allows each token in a sequence to 'pay attention' to every other token when computing its representation. This enables models to capture long-range dependencies in text — understanding that 'it' in a sentence refers to something mentioned several paragraphs earlier. Multi-head attention runs this process in parallel multiple times to capture different types of relationships.", relatedTerms: ["transformer", "llm"], lastUpdated: "2026-04-11" },
  { term: "Fine-tuning", slug: "fine-tuning", category: "Training", definition: "Further training a pre-trained AI model on a smaller, task-specific dataset to specialize its behavior.", expanded: "Pre-trained foundation models are general-purpose. Fine-tuning adapts them for specific use cases — a customer support chatbot, a medical coding tool, or a legal document analyzer. It's far cheaper than training from scratch. Techniques include supervised fine-tuning (SFT) on examples of desired behavior, and RLHF to align with human preferences.", example: "OpenAI fine-tunes GPT-4 on customer service conversations to create specialized support chatbots.", relatedTerms: ["rlhf", "foundation-model", "llm"], lastUpdated: "2026-04-11" },
  { term: "RLHF", slug: "rlhf", category: "Training", definition: "Reinforcement Learning from Human Feedback — a training technique used to align AI models with human preferences and values.", expanded: "RLHF involves: 1) Fine-tuning the base model on demonstration data, 2) Training a reward model on human preference comparisons (which output is better?), 3) Using reinforcement learning to optimize the LLM to produce outputs the reward model scores highly. This is how ChatGPT, Claude, and Gemini are aligned to be helpful and safe, rather than just predicting text statistically.", relatedTerms: ["fine-tuning", "alignment", "constitutional-ai"], lastUpdated: "2026-04-11" },
  { term: "RAG (Retrieval Augmented Generation)", slug: "rag", category: "Techniques", definition: "A technique that enhances LLM responses by retrieving relevant documents from an external knowledge base before generating an answer.", expanded: "RAG solves two key LLM problems: knowledge cutoff dates and hallucination. Instead of relying solely on training data, RAG retrieves current, relevant documents from a database (using vector search) and provides them as context to the LLM. The model then generates an answer grounded in real retrieved documents. Used by Perplexity AI, enterprise chatbots, and most production AI applications.", example: "A customer service chatbot uses RAG to retrieve the latest product documentation before answering support questions.", relatedTerms: ["vector-database", "embeddings", "grounding", "hallucination"], lastUpdated: "2026-04-11" },
  { term: "Embeddings", slug: "embeddings", category: "Techniques", definition: "Numerical vector representations of text that capture semantic meaning, allowing AI to find conceptually similar content.", expanded: "When you convert text to embeddings, semantically similar sentences end up as nearby vectors in high-dimensional space. 'The cat sat on the mat' and 'A feline rested on the rug' would have similar embedding vectors. Embeddings power semantic search (finding relevant documents by meaning, not just keywords) and are the foundation of RAG systems and vector databases.", example: "OpenAI's text-embedding-3-large model converts text into 3,072-dimensional vectors for semantic search.", relatedTerms: ["rag", "vector-database", "semantic-search"], lastUpdated: "2026-04-11" },
  { term: "Vector Database", slug: "vector-database", category: "Infrastructure", definition: "A database optimized for storing and searching embedding vectors — the foundation of RAG and semantic search applications.", expanded: "Traditional databases search by exact matching. Vector databases find the nearest neighbors in embedding space — returning documents semantically similar to a query. Popular options include Pinecone, Weaviate, Qdrant, Chroma, and pgvector (PostgreSQL extension). They're the backbone of every enterprise RAG application.", example: "Pinecone, Weaviate, and pgvector are popular vector databases used in AI applications.", relatedTerms: ["embeddings", "rag", "semantic-search"], lastUpdated: "2026-04-11" },
  { term: "Temperature", slug: "temperature", category: "Parameters", definition: "A parameter (0 to 2) that controls how random or deterministic an AI model's outputs are.", expanded: "At temperature 0, the model always picks the most likely next token — highly deterministic and repetitive. At higher temperatures (1-2), lower-probability tokens are sampled more often — producing more varied, creative outputs but potentially less coherent. For factual tasks, use low temperature. For creative writing or brainstorming, use higher temperature.", example: "Temperature 0 for consistent, repeatable outputs. Temperature 0.7-1.0 for creative tasks.", relatedTerms: ["top-p", "llm", "prompt-engineering"], lastUpdated: "2026-04-11" },
  { term: "Top-P (Nucleus Sampling)", slug: "top-p", category: "Parameters", definition: "A sampling parameter that limits token selection to the smallest set of tokens whose cumulative probability exceeds P.", expanded: "Top-P (also called nucleus sampling) is an alternative to temperature for controlling output randomness. Instead of scaling all probabilities, it only considers tokens whose probabilities sum to P (e.g., 0.9). This allows natural diversity while preventing very unlikely tokens from being selected. Most production systems tune both temperature and top-P together.", relatedTerms: ["temperature", "llm"], lastUpdated: "2026-04-11" },
  { term: "System Prompt", slug: "system-prompt", category: "Techniques", definition: "Instructions given to an AI model before the user conversation begins, shaping its behavior, persona, and constraints.", expanded: "The system prompt is the 'instruction layer' of an AI application. It might define a persona ('You are a helpful customer support agent for Acme Corp'), set constraints ('Never discuss competitor products'), or provide context ('You have access to the following product catalog'). System prompts are typically invisible to end users and are how AI products are customized.", example: "ChatGPT's system prompt defines its personality, safety guidelines, and knowledge boundaries.", relatedTerms: ["prompt-engineering", "llm", "context-window"], lastUpdated: "2026-04-11" },
  { term: "Zero-shot Learning", slug: "zero-shot", category: "Techniques", definition: "Asking an AI to perform a task it wasn't explicitly trained on, relying solely on its general capabilities.", expanded: "Zero-shot means giving the model no examples — just a description of the task. 'Classify this review as positive, negative, or neutral' without showing any labeled examples. Modern LLMs perform remarkably well zero-shot on many tasks due to their vast training data. Zero-shot is cheaper than few-shot (no examples in prompt) and often sufficient for standard tasks.", relatedTerms: ["few-shot", "prompt-engineering"], lastUpdated: "2026-04-11" },
  { term: "Few-shot Learning", slug: "few-shot", category: "Techniques", definition: "Providing a small number of input-output examples in the prompt to guide the AI's response format and style.", expanded: "Few-shot prompting dramatically improves performance on structured tasks by showing the model exactly what format you want. Instead of describing the task, you show 2-5 examples of desired input→output pairs. The model infers the pattern and applies it to new inputs. Particularly effective for classification, data extraction, and stylistic writing tasks.", example: "Providing 3 example customer reviews with sentiment labels before asking the model to classify new reviews.", relatedTerms: ["zero-shot", "prompt-engineering"], lastUpdated: "2026-04-11" },
  { term: "Chain of Thought (CoT)", slug: "chain-of-thought", category: "Techniques", definition: "A prompting technique where the AI is guided to reason step-by-step before producing a final answer, significantly improving accuracy on complex tasks.", expanded: "Simply adding 'Let's think step by step' to a prompt — or showing examples of step-by-step reasoning — dramatically improves LLM performance on math, logic, and multi-step reasoning tasks. Chain of thought works because it forces the model to allocate more 'compute' to reasoning rather than jumping to an answer.", example: "Instead of asking 'What is 25% of 480?', ask 'What is 25% of 480? Let's think step by step.'", relatedTerms: ["prompt-engineering", "few-shot", "reasoning-model"], lastUpdated: "2026-04-11" },
  { term: "AI Agent", slug: "ai-agent", category: "Applications", definition: "An AI system that can autonomously take actions, use tools, and complete multi-step tasks without human intervention at each step.", expanded: "Unlike a chatbot that answers questions, an AI agent plans and executes sequences of actions to achieve a goal. It uses tools (web search, code execution, file access, APIs) and makes decisions about what to do next based on results. Examples: Claude Code (writes and runs code autonomously), Devin (autonomous software engineer), AI agents that manage email workflows.", example: "Claude Code is an AI agent that can read your codebase, write code, run tests, and fix errors autonomously.", relatedTerms: ["tool-use", "function-calling", "llm"], lastUpdated: "2026-04-11" },
  { term: "Tool Use / Function Calling", slug: "tool-use", category: "Applications", definition: "The ability for AI models to call external functions, APIs, or tools to retrieve information or take actions beyond their training data.", expanded: "Function calling allows LLMs to interface with the real world. The model is given descriptions of available tools (e.g., 'search_web(query)', 'get_weather(city)', 'send_email(to, subject, body)') and decides when to call them. This is how ChatGPT plugins work, how AI agents retrieve current information, and how enterprise AI integrates with business systems.", relatedTerms: ["ai-agent", "structured-output"], lastUpdated: "2026-04-11" },
  { term: "Grounding", slug: "grounding", category: "Techniques", definition: "Connecting AI model responses to verified, real-world information sources to reduce hallucination and improve accuracy.", expanded: "Grounding means the AI's responses are anchored to specific documents, data sources, or real-time web results — rather than generated purely from training data. RAG is a grounding technique. Web search integration (Perplexity, Gemini with Google Search) is grounding. Enterprise deployments ground AI on internal knowledge bases. Grounding is the primary solution to hallucination.", relatedTerms: ["rag", "hallucination", "vector-database"], lastUpdated: "2026-04-11" },
  { term: "Foundation Model", slug: "foundation-model", category: "Core Concepts", definition: "A large AI model trained on broad data at scale that can be adapted for many different downstream tasks.", expanded: "The term was coined by Stanford's Center for Research on Foundation Models in 2021. Foundation models (GPT-4, Claude, Gemini, LLaMA) are trained once at enormous scale, then fine-tuned or prompted for specific applications. The 'foundation' metaphor captures that these models form the base layer for thousands of AI applications built on top.", relatedTerms: ["llm", "fine-tuning", "transformer"], lastUpdated: "2026-04-11" },
  { term: "Multimodal AI", slug: "multimodal", category: "Core Concepts", definition: "AI systems that can process and generate multiple types of data — text, images, audio, video, and code.", expanded: "Early AI models handled only one modality (text-only or image-only). Modern multimodal models like GPT-4o, Gemini Ultra, and Claude 3 can accept images, audio, and documents alongside text. This enables use cases like analyzing a photograph, describing a video, reading a chart, or answering questions about a PDF — all in natural language.", example: "GPT-4o can analyze a photo of a restaurant menu and recommend dishes based on dietary restrictions.", relatedTerms: ["llm", "foundation-model"], lastUpdated: "2026-04-11" },
  { term: "Inference", slug: "inference", category: "Infrastructure", definition: "The process of running a trained AI model to generate outputs — what happens when you use an AI tool.", expanded: "Training creates an AI model. Inference is using that model to generate predictions or responses. Inference costs and latency are what AI companies optimize for commercial deployment. Inference is measured in tokens per second and cost per token. Faster, cheaper inference is achieved through hardware optimization (GPUs/TPUs), model distillation, quantization, and batching.", relatedTerms: ["latency", "llm", "token"], lastUpdated: "2026-04-11" },
  { term: "Latency", slug: "latency", category: "Performance", definition: "The time delay between sending a request to an AI API and receiving the first token of response.", expanded: "Latency matters enormously for user experience. For chat interfaces, time-to-first-token (TTFT) should be under 1 second. For real-time voice AI, latency must be under 300ms. For batch processing, throughput matters more than latency. Different models have very different latency profiles — Claude Haiku is much faster than Claude Opus at the cost of capability.", relatedTerms: ["inference", "throughput", "token"], lastUpdated: "2026-04-11" },
  { term: "Knowledge Cutoff", slug: "knowledge-cutoff", category: "Core Concepts", definition: "The date after which an AI model has no training data — the 'last updated' date of its knowledge.", expanded: "LLMs are trained on snapshots of the internet up to a certain date. After that date, they have no awareness of new events, product releases, or research. GPT-4o has a knowledge cutoff of early 2024. Claude has a similar cutoff. This is why AI tools hallucinate about recent events or give outdated information. Web search integration (Perplexity, Gemini) solves this.", relatedTerms: ["hallucination", "rag", "grounding"], lastUpdated: "2026-04-11" },
  { term: "Alignment", slug: "alignment", category: "Safety", definition: "The challenge of ensuring AI systems behave in accordance with human values, intentions, and societal well-being.", expanded: "AI alignment is one of the central problems in AI safety. A misaligned AI pursues goals that differ from its creators' intentions — either through specification errors (we gave it the wrong goal), capability overhang (it's more capable than we realized), or mesa-optimization (it develops its own sub-goals during training). RLHF, Constitutional AI, and scalable oversight are current alignment techniques.", relatedTerms: ["rlhf", "constitutional-ai", "safety"], lastUpdated: "2026-04-11" },
  { term: "Constitutional AI", slug: "constitutional-ai", category: "Safety", definition: "Anthropic's technique for training Claude to be helpful, harmless, and honest by having AI models critique and revise their own outputs based on a set of principles.", expanded: "Constitutional AI (CAI) involves two phases: 1) Supervised learning phase where the model revises its responses to comply with a 'constitution' of principles, 2) RL phase where a preference model trained on AI feedback (not human feedback) guides further training. This allows scaling alignment supervision with less human labeling. It's how Claude was made safer than models trained with pure RLHF.", relatedTerms: ["rlhf", "alignment", "fine-tuning"], lastUpdated: "2026-04-11" },
  { term: "Diffusion Model", slug: "diffusion-model", category: "Architecture", definition: "The AI architecture behind most image, audio, and video generation — learns to reverse a noise-adding process to generate content.", expanded: "Diffusion models work by gradually adding Gaussian noise to training data until it becomes pure noise, then training a neural network to reverse this process. During generation, the model starts from random noise and iteratively denoises it into a coherent image or audio clip. Stable Diffusion, DALL-E 3, Midjourney, Sora, and most modern image/video generators use diffusion-based architectures.", relatedTerms: ["transformer", "multimodal"], lastUpdated: "2026-04-11" },
  { term: "Reasoning Model", slug: "reasoning-model", category: "Core Concepts", definition: "AI models specifically optimized for multi-step logical reasoning, math, and complex problem-solving — typically by using chain-of-thought at inference time.", expanded: "Reasoning models (OpenAI o1, Claude's extended thinking mode, Gemini Thinking) use 'test-time compute' — spending more tokens on internal reasoning before answering. They think through problems step by step internally, trading speed for accuracy on hard tasks. Best for math, coding, science, and multi-step logical problems. More expensive and slower than standard models.", example: "OpenAI o1 uses extended reasoning to solve math competition problems that GPT-4o gets wrong.", relatedTerms: ["chain-of-thought", "llm", "benchmark"], lastUpdated: "2026-04-11" },
  { term: "Agentic AI", slug: "agentic-ai", category: "Applications", definition: "AI systems that operate autonomously over extended periods, taking sequences of actions to complete complex goals.", expanded: "Agentic AI goes beyond single-turn responses. Agentic systems plan, act, observe results, and adapt — running for minutes or hours on complex tasks. Multi-agent systems coordinate multiple specialized AI agents. Examples: AI research assistants that search, read papers, and write reports; AI software engineers that write, test, and debug code; AI operations assistants that monitor systems and respond to incidents.", relatedTerms: ["ai-agent", "tool-use", "function-calling"], lastUpdated: "2026-04-11" },
  { term: "Structured Output", slug: "structured-output", category: "Techniques", definition: "Constraining an AI model to generate responses in a specific format (JSON, XML, etc.) for reliable programmatic processing.", expanded: "By default, LLMs generate free-form text. Structured outputs force the model to produce valid JSON (or other formats) matching a specified schema. This is essential for production AI applications — you can reliably extract data, fill databases, and process AI outputs programmatically without fragile string parsing. OpenAI, Anthropic, and Google all offer structured output modes.", relatedTerms: ["tool-use", "function-calling"], lastUpdated: "2026-04-11" },
  { term: "Tokenization", slug: "tokenization", category: "Core Concepts", definition: "The process of splitting text into tokens (the basic units an LLM processes) before feeding it to a model.", expanded: "Different models use different tokenization approaches. GPT models use Byte Pair Encoding (BPE). One token is ~4 characters in English, but the ratio varies by language — Chinese, Japanese, and Korean use more tokens per character. Tokenization affects cost (API pricing is per token), context window usage, and model performance on non-English languages.", relatedTerms: ["token", "llm", "context-window"], lastUpdated: "2026-04-11" },
  { term: "Benchmark", slug: "benchmark", category: "Evaluation", definition: "A standardized test used to measure and compare AI model capabilities across specific tasks.", expanded: "Common benchmarks include: MMLU (massive multitask language understanding — college-level knowledge), HumanEval (coding ability), MATH-500 (competition math), MT-Bench (multi-turn conversation), HellaSwag (common sense reasoning). Benchmarks enable objective comparisons but can be 'gamed' by training on similar data. Real-world performance often differs from benchmark scores.", example: "GPT-4o scores 86% on MMLU. Claude Opus 4 scores 88%. Gemini 2.5 Pro scores 90%.", relatedTerms: ["llm", "reasoning-model"], lastUpdated: "2026-04-11" },
  { term: "Open Source AI", slug: "open-source-ai", category: "Core Concepts", definition: "AI models whose weights and (sometimes) training code are publicly released, allowing anyone to run, modify, and build on them.", expanded: "Open source AI (Meta's LLaMA, Mistral, Stable Diffusion) contrasts with closed models (GPT-4, Claude, Gemini) where the weights are proprietary. Open models can be run locally (full privacy), fine-tuned for specific use cases, and deployed without per-token API fees. The quality gap between open and closed models has narrowed significantly — LLaMA 3.1 405B is competitive with GPT-4o.", relatedTerms: ["fine-tuning", "foundation-model", "llm"], lastUpdated: "2026-04-11" },
  { term: "API (Application Programming Interface)", slug: "api", category: "Infrastructure", definition: "A software interface that allows developers to access AI model capabilities programmatically — the foundation of all AI-powered products.", expanded: "AI APIs let developers build applications on top of powerful models without training their own. You send a request (with your prompt and API key) and receive the model's response. OpenAI, Anthropic, Google, and Mistral all offer commercial APIs. Pricing is typically per million input/output tokens. Rate limits prevent overuse.", relatedTerms: ["token", "inference", "rate-limit"], lastUpdated: "2026-04-11" },
  { term: "Rate Limit", slug: "rate-limit", category: "Infrastructure", definition: "Constraints imposed by AI API providers on how many requests or tokens a user can process per minute, hour, or day.", expanded: "Rate limits exist to prevent abuse, manage server capacity, and ensure fair access. They're typically measured in RPM (requests per minute), RPD (requests per day), and TPM (tokens per minute). Enterprise tiers have higher limits. Exceeding rate limits returns 429 errors. Strategies to handle limits include queuing, batching, and exponential backoff.", relatedTerms: ["api", "inference", "token"], lastUpdated: "2026-04-11" },
  { term: "Semantic Search", slug: "semantic-search", category: "Techniques", definition: "Search that finds results based on meaning and intent, not just keyword matching.", expanded: "Traditional search finds documents containing specific keywords. Semantic search uses embeddings to find documents with similar meaning, even if they use different words. Searching for 'how to fix a flat tire' would also surface documents about 'puncture repair' and 'changing a wheel'. AI-powered search (Perplexity, Bing Chat, Google AI Overview) uses semantic search to improve relevance.", relatedTerms: ["embeddings", "vector-database", "rag"], lastUpdated: "2026-04-11" },
  { term: "AI Safety", slug: "safety", category: "Safety", definition: "The field of research and practice focused on building AI systems that are safe, reliable, controllable, and aligned with human values.", expanded: "AI safety encompasses near-term concerns (bias, misuse, copyright) and long-term concerns (misaligned superintelligent AI). Key organizations: Anthropic, OpenAI's safety team, DeepMind Safety, and Alignment Research Center. Current techniques include RLHF, red-teaming, constitutional AI, interpretability research, and scalable oversight. The pace of AI capability advancement makes safety research increasingly urgent.", relatedTerms: ["alignment", "rlhf", "constitutional-ai"], lastUpdated: "2026-04-11" },
  { term: "Quantization", slug: "quantization", category: "Infrastructure", definition: "A technique for reducing AI model size and memory requirements by representing weights with lower precision numbers.", expanded: "A full-precision model stores weights as 32-bit floats. 4-bit quantization reduces each weight to 4 bits — an 8x size reduction with modest quality loss. This makes large models runnable on consumer hardware. LLaMA 3.1 405B in full precision requires 810GB VRAM; 4-bit quantized versions run on a single A100 80GB GPU. Tools: llama.cpp, GGUF format, bitsandbytes.", relatedTerms: ["open-source-ai", "inference", "llm"], lastUpdated: "2026-04-11" },
  { term: "Model Distillation", slug: "model-distillation", category: "Training", definition: "Training a smaller AI model to mimic a larger, more capable model — creating efficient models that approach the larger model's quality.", expanded: "In distillation, the small 'student' model is trained not just on data, but on the outputs of the large 'teacher' model. The student learns to replicate the teacher's behavior patterns. This produces models much more capable than their size suggests. GPT-4o mini is distilled from GPT-4o. Many small, fast models are distillations of larger frontier models.", relatedTerms: ["fine-tuning", "llm", "inference"], lastUpdated: "2026-04-11" },
];

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return glossaryTerms.find((t) => t.slug === slug);
}

export const GLOSSARY_CATEGORIES = [...new Set(glossaryTerms.map((t) => t.category))];

export function getTermsByLetter(): Record<string, GlossaryTerm[]> {
  return glossaryTerms.reduce((acc, term) => {
    const letter = term.term[0].toUpperCase();
    if (!acc[letter]) acc[letter] = [];
    acc[letter].push(term);
    return acc;
  }, {} as Record<string, GlossaryTerm[]>);
}
