import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const providers = [
  // Tier 1 — Frontier LLM Labs
  { name: "OpenAI", slug: "openai", tier: 1, website: "https://openai.com", apiKeyEnv: "OPENAI_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.openai.com/v1", order: 1 },
  { name: "Google DeepMind", slug: "google-deepmind", tier: 1, website: "https://deepmind.google", apiKeyEnv: "GEMINI_API_KEY", apiFormat: "gemini", apiBaseUrl: null, order: 2 },
  { name: "Anthropic", slug: "anthropic", tier: 1, website: "https://anthropic.com", apiKeyEnv: "ANTHROPIC_API_KEY", apiFormat: "anthropic", apiBaseUrl: null, order: 3 },
  { name: "Meta AI", slug: "meta-ai", tier: 1, website: "https://ai.meta.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 4 },
  { name: "xAI", slug: "xai", tier: 1, website: "https://x.ai", apiKeyEnv: "XAI_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.x.ai/v1", order: 5 },
  { name: "Mistral AI", slug: "mistral-ai", tier: 1, website: "https://mistral.ai", apiKeyEnv: "MISTRAL_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.mistral.ai/v1", order: 6 },
  { name: "DeepSeek", slug: "deepseek", tier: 1, website: "https://deepseek.com", apiKeyEnv: "DEEPSEEK_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.deepseek.com/v1", order: 7 },
  { name: "Cohere", slug: "cohere", tier: 1, website: "https://cohere.com", apiKeyEnv: "COHERE_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.cohere.ai/compatibility/v1", order: 8 },
  { name: "AI21 Labs", slug: "ai21-labs", tier: 1, website: "https://ai21.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 9 },
  { name: "Aleph Alpha", slug: "aleph-alpha", tier: 1, website: "https://aleph-alpha.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 10 },
  { name: "Microsoft AI", slug: "microsoft-ai", tier: 1, website: "https://azure.microsoft.com/en-us/products/ai-services", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 11 },
  { name: "NVIDIA AI", slug: "nvidia-ai", tier: 1, website: "https://build.nvidia.com", apiKeyEnv: "NVIDIA_API_KEY", apiFormat: "openai", apiBaseUrl: "https://integrate.api.nvidia.com/v1", order: 12 },
  { name: "Amazon AWS AI", slug: "amazon-aws-ai", tier: 1, website: "https://aws.amazon.com/bedrock", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 13 },
  { name: "IBM Research AI", slug: "ibm-research-ai", tier: 1, website: "https://www.ibm.com/watson", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 14 },
  { name: "Baidu", slug: "baidu", tier: 1, website: "https://cloud.baidu.com/product/wenxinworkshop", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 15 },

  // Tier 2 — Major Global LLM Builders
  { name: "Alibaba DAMO Academy", slug: "alibaba-damo", tier: 2, website: "https://tongyi.aliyun.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 16 },
  { name: "Tencent AI Lab", slug: "tencent-ai", tier: 2, website: "https://ai.tencent.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 17 },
  { name: "Huawei Noah's Ark Lab", slug: "huawei-noahs-ark", tier: 2, website: "https://www.noahlab.com.hk", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 18 },
  { name: "Naver HyperCLOVA", slug: "naver-hyperclova", tier: 2, website: "https://clova.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 19 },
  { name: "Yandex AI", slug: "yandex-ai", tier: 2, website: "https://ya.ru/ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 20 },
  { name: "TII (Falcon)", slug: "tii-falcon", tier: 2, website: "https://falconllm.tii.ae", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 21 },
  { name: "Stability AI", slug: "stability-ai", tier: 2, website: "https://stability.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 22 },
  { name: "Databricks", slug: "databricks", tier: 2, website: "https://databricks.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 23 },
  { name: "Snowflake AI", slug: "snowflake-ai", tier: 2, website: "https://snowflake.com/en/data-cloud/arctic", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 24 },
  { name: "Perplexity AI", slug: "perplexity-ai", tier: 2, website: "https://perplexity.ai", apiKeyEnv: "PERPLEXITY_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.perplexity.ai", order: 25 },
  { name: "Together AI", slug: "together-ai", tier: 2, website: "https://together.ai", apiKeyEnv: "TOGETHER_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.together.xyz/v1", order: 26 },
  { name: "Writer", slug: "writer", tier: 2, website: "https://writer.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 27 },
  { name: "Character.AI", slug: "character-ai", tier: 2, website: "https://character.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 28 },
  { name: "Inflection AI", slug: "inflection-ai", tier: 2, website: "https://inflection.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 29 },
  { name: "Adept AI", slug: "adept-ai", tier: 2, website: "https://adept.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 30 },
  { name: "Sakana AI", slug: "sakana-ai", tier: 2, website: "https://sakana.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 31 },
  { name: "Reka AI", slug: "reka-ai", tier: 2, website: "https://reka.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 32 },
  { name: "Moonshot AI (Kimi)", slug: "moonshot-ai", tier: 2, website: "https://moonshot.cn", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 33 },
  { name: "MiniMax AI", slug: "minimax-ai", tier: 2, website: "https://minimax.io", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 34 },
  { name: "01.AI", slug: "01-ai", tier: 2, website: "https://01.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 35 },

  // Tier 3 — Open Model / Research LLM Labs
  { name: "MosaicML (Databricks)", slug: "mosaicml", tier: 3, website: "https://mosaicml.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 36 },
  { name: "BigScience (BLOOM)", slug: "bigscience", tier: 3, website: "https://bigscience.huggingface.co", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 37 },
  { name: "Hugging Face", slug: "hugging-face", tier: 3, website: "https://huggingface.co", apiKeyEnv: "HF_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api-inference.huggingface.co/v1", order: 38 },
  { name: "EleutherAI", slug: "eleutherai", tier: 3, website: "https://eleuther.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 39 },
  { name: "LAION", slug: "laion", tier: 3, website: "https://laion.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 40 },
  { name: "OpenChat", slug: "openchat", tier: 3, website: "https://openchat.team", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 41 },
  { name: "Nous Research", slug: "nous-research", tier: 3, website: "https://nousresearch.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 42 },
  { name: "OpenAssistant", slug: "openassistant", tier: 3, website: "https://open-assistant.io", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 43 },
  { name: "RWKV Foundation", slug: "rwkv-foundation", tier: 3, website: "https://rwkv.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 44 },
  { name: "OpenMMLab", slug: "openmmlab", tier: 3, website: "https://openmmlab.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 45 },
  { name: "KoboldAI", slug: "koboldai", tier: 3, website: "https://koboldai.org", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 46 },
  { name: "OpenBMB", slug: "openbmb", tier: 3, website: "https://openbmb.org", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 47 },
  { name: "THUDM (ChatGLM)", slug: "thudm", tier: 3, website: "https://chatglm.cn", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 48 },
  { name: "Shanghai AI Lab", slug: "shanghai-ai-lab", tier: 3, website: "https://www.shlab.org.cn", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 49 },
  { name: "IDEA Research", slug: "idea-research", tier: 3, website: "https://idea.edu.cn", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 50 },
  { name: "Berkeley AI Research (BAIR)", slug: "bair", tier: 3, website: "https://bair.berkeley.edu", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 51 },
  { name: "Stanford CRFM", slug: "stanford-crfm", tier: 3, website: "https://crfm.stanford.edu", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 52 },
  { name: "MIT CSAIL", slug: "mit-csail", tier: 3, website: "https://www.csail.mit.edu", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 53 },
  { name: "Allen Institute for AI (AI2)", slug: "ai2", tier: 3, website: "https://allenai.org", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 54 },
  { name: "University of Toronto Vector Institute", slug: "vector-institute", tier: 3, website: "https://vectorinstitute.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 55 },
  { name: "MILA", slug: "mila", tier: 3, website: "https://mila.quebec", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 56 },
  { name: "Tsinghua KEG Lab", slug: "tsinghua-keg", tier: 3, website: "https://keg.cs.tsinghua.edu.cn", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 57 },
  { name: "Zhejiang Lab", slug: "zhejiang-lab", tier: 3, website: "https://en.zhejianglab.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 58 },
  { name: "PKU AI Lab", slug: "pku-ai-lab", tier: 3, website: "https://www.pku.edu.cn", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 59 },
  { name: "HKUST AI Lab", slug: "hkust-ai-lab", tier: 3, website: "https://www.hkust.edu.hk", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 60 },

  // Tier 4 — Enterprise LLM Builders
  { name: "SAP AI", slug: "sap-ai", tier: 4, website: "https://www.sap.com/products/artificial-intelligence.html", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 61 },
  { name: "Oracle AI", slug: "oracle-ai", tier: 4, website: "https://www.oracle.com/artificial-intelligence", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 62 },
  { name: "ServiceNow AI", slug: "servicenow-ai", tier: 4, website: "https://www.servicenow.com/products/now-intelligence.html", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 63 },
  { name: "Salesforce AI (Einstein)", slug: "salesforce-ai", tier: 4, website: "https://www.salesforce.com/products/einstein", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 64 },
  { name: "Adobe AI", slug: "adobe-ai", tier: 4, website: "https://www.adobe.com/sensei.html", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 65 },
  { name: "Zoom AI", slug: "zoom-ai", tier: 4, website: "https://zoom.us/ai-companion", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 66 },
  { name: "Grammarly AI", slug: "grammarly-ai", tier: 4, website: "https://www.grammarly.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 67 },
  { name: "Notion AI", slug: "notion-ai", tier: 4, website: "https://www.notion.so/product/ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 68 },
  { name: "Atlassian AI", slug: "atlassian-ai", tier: 4, website: "https://www.atlassian.com/platform/ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 69 },
  { name: "Box AI", slug: "box-ai", tier: 4, website: "https://www.box.com/ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 70 },
  { name: "Dropbox AI", slug: "dropbox-ai", tier: 4, website: "https://www.dropbox.com/features/ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 71 },
  { name: "Quora (Poe models)", slug: "quora-poe", tier: 4, website: "https://poe.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 72 },
  { name: "Canva AI", slug: "canva-ai", tier: 4, website: "https://www.canva.com/magic-studio", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 73 },
  { name: "Descript AI", slug: "descript-ai", tier: 4, website: "https://www.descript.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 74 },
  { name: "Jasper AI", slug: "jasper-ai", tier: 4, website: "https://www.jasper.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 75 },
  { name: "Copy.ai", slug: "copy-ai", tier: 4, website: "https://www.copy.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 76 },
  { name: "Writesonic", slug: "writesonic", tier: 4, website: "https://writesonic.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 77 },
  { name: "Anyword", slug: "anyword", tier: 4, website: "https://anyword.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 78 },
  { name: "Typeface AI", slug: "typeface-ai", tier: 4, website: "https://www.typeface.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 79 },
  { name: "Runway ML", slug: "runway-ml", tier: 4, website: "https://runwayml.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 80 },

  // Tier 5 — Regional LLM Builders
  { name: "SenseTime", slug: "sensetime", tier: 5, website: "https://www.sensetime.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 81 },
  { name: "iFlytek", slug: "iflytek", tier: 5, website: "https://www.iflytek.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 82 },
  { name: "Zhipu AI", slug: "zhipu-ai", tier: 5, website: "https://zhipuai.cn", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 83 },
  { name: "Baichuan AI", slug: "baichuan-ai", tier: 5, website: "https://www.baichuan-ai.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 84 },
  { name: "StepFun AI", slug: "stepfun-ai", tier: 5, website: "https://stepfun.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 85 },
  { name: "Kunlun AI", slug: "kunlun-ai", tier: 5, website: "https://www.kunlun.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 86 },
  { name: "Lingyi Wanwu", slug: "lingyi-wanwu", tier: 5, website: "https://www.lingyiwanwu.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 87 },
  { name: "LightOn AI", slug: "lighton-ai", tier: 5, website: "https://lighton.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 88 },
  { name: "MPT (MosaicML)", slug: "mpt-mosaicml", tier: 5, website: "https://www.mosaicml.com/mpt", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 89 },
  { name: "Cerebras AI", slug: "cerebras-ai", tier: 5, website: "https://cerebras.ai", apiKeyEnv: "CEREBRAS_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.cerebras.ai/v1", order: 90 },
  { name: "Groq AI", slug: "groq-ai", tier: 5, website: "https://groq.com", apiKeyEnv: "GROQ_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.groq.com/openai/v1", order: 91 },
  { name: "OctoAI", slug: "octoai", tier: 5, website: "https://octoai.cloud", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 92 },
  { name: "Fireworks AI", slug: "fireworks-ai", tier: 5, website: "https://fireworks.ai", apiKeyEnv: "FIREWORKS_API_KEY", apiFormat: "openai", apiBaseUrl: "https://api.fireworks.ai/inference/v1", order: 93 },
  { name: "Baseten", slug: "baseten", tier: 5, website: "https://baseten.co", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 94 },
  { name: "Modular AI", slug: "modular-ai", tier: 5, website: "https://www.modular.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 95 },
  { name: "Replit AI", slug: "replit-ai", tier: 5, website: "https://replit.com/ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 96 },
  { name: "Codeium AI", slug: "codeium-ai", tier: 5, website: "https://codeium.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 97 },
  { name: "Phind AI", slug: "phind-ai", tier: 5, website: "https://phind.com", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 98 },
  { name: "Magic AI", slug: "magic-ai", tier: 5, website: "https://magic.dev", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 99 },
  { name: "Liquid AI", slug: "liquid-ai", tier: 5, website: "https://liquid.ai", apiKeyEnv: null, apiFormat: "openai", apiBaseUrl: null, order: 100 },
];

// Initial models for providers that have active API keys configured
const initialModels = [
  // OpenAI models
  {
    providerSlug: "openai",
    name: "GPT-4o",
    slug: "gpt-4o",
    modelId: "gpt-4o",
    description: "Most capable GPT-4 multimodal model",
    initial: "G",
    colorClass: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400",
    borderClass: "border-emerald-500/20",
    gradientClass: "from-emerald-500/10 to-emerald-500/5",
    order: 1,
  },
  {
    providerSlug: "openai",
    name: "GPT-4o Mini",
    slug: "gpt-4o-mini",
    modelId: "gpt-4o-mini",
    description: "Lightweight and fast GPT-4o model",
    initial: "G",
    colorClass: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400",
    borderClass: "border-emerald-500/20",
    gradientClass: "from-emerald-500/10 to-emerald-500/5",
    order: 2,
  },
  {
    providerSlug: "openai",
    name: "o3 Mini",
    slug: "o3-mini",
    modelId: "o3-mini",
    description: "OpenAI o3 reasoning model — mini",
    initial: "G",
    colorClass: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400",
    borderClass: "border-emerald-500/20",
    gradientClass: "from-emerald-500/10 to-emerald-500/5",
    order: 3,
  },
  // Anthropic models — Claude 4.x series (latest)
  {
    providerSlug: "anthropic",
    name: "Claude Opus 4.6",
    slug: "claude-opus-4-6",
    modelId: "claude-opus-4-6",
    description: "Most powerful Claude 4.6 model",
    initial: "C",
    colorClass: "bg-orange-500/10 text-orange-700 dark:text-orange-400",
    borderClass: "border-orange-500/20",
    gradientClass: "from-orange-500/10 to-orange-500/5",
    order: 1,
  },
  {
    providerSlug: "anthropic",
    name: "Claude Sonnet 4.6",
    slug: "claude-sonnet-4-6",
    modelId: "claude-sonnet-4-6",
    description: "Balanced Claude 4.6 model",
    initial: "C",
    colorClass: "bg-orange-500/10 text-orange-700 dark:text-orange-400",
    borderClass: "border-orange-500/20",
    gradientClass: "from-orange-500/10 to-orange-500/5",
    order: 2,
  },
  {
    providerSlug: "anthropic",
    name: "Claude Opus 4.5",
    slug: "claude-opus-4-5",
    modelId: "claude-opus-4-5",
    description: "Powerful Claude 4.5 model",
    initial: "C",
    colorClass: "bg-orange-500/10 text-orange-700 dark:text-orange-400",
    borderClass: "border-orange-500/20",
    gradientClass: "from-orange-500/10 to-orange-500/5",
    order: 3,
  },
  {
    providerSlug: "anthropic",
    name: "Claude Sonnet 4.5",
    slug: "claude-sonnet-4-5",
    modelId: "claude-sonnet-4-5",
    description: "Balanced Claude 4.5 model",
    initial: "C",
    colorClass: "bg-orange-500/10 text-orange-700 dark:text-orange-400",
    borderClass: "border-orange-500/20",
    gradientClass: "from-orange-500/10 to-orange-500/5",
    order: 4,
  },
  {
    providerSlug: "anthropic",
    name: "Claude Haiku 4.5",
    slug: "claude-haiku-4-5",
    modelId: "claude-haiku-4-5-20251001",
    description: "Fastest and most compact Claude 4.5 model",
    initial: "C",
    colorClass: "bg-orange-500/10 text-orange-700 dark:text-orange-400",
    borderClass: "border-orange-500/20",
    gradientClass: "from-orange-500/10 to-orange-500/5",
    order: 5,
  },
  // Anthropic models — Claude 4 base generation
  {
    providerSlug: "anthropic",
    name: "Claude Opus 4",
    slug: "claude-opus-4",
    modelId: "claude-opus-4-0",
    description: "Claude 4 base Opus model",
    initial: "C",
    colorClass: "bg-orange-500/10 text-orange-700 dark:text-orange-400",
    borderClass: "border-orange-500/20",
    gradientClass: "from-orange-500/10 to-orange-500/5",
    order: 6,
  },
  {
    providerSlug: "anthropic",
    name: "Claude Sonnet 4",
    slug: "claude-sonnet-4",
    modelId: "claude-sonnet-4-0",
    description: "Claude 4 base Sonnet model",
    initial: "C",
    colorClass: "bg-orange-500/10 text-orange-700 dark:text-orange-400",
    borderClass: "border-orange-500/20",
    gradientClass: "from-orange-500/10 to-orange-500/5",
    order: 7,
  },
  // Google DeepMind models — Gemini 3 series (latest/recommended)
  {
    providerSlug: "google-deepmind",
    name: "Gemini 3.1 Pro (Preview)",
    slug: "gemini-3-1-pro",
    modelId: "gemini-3.1-pro-preview",
    description: "Latest Gemini 3.1 Pro with improved reasoning and multimodal capabilities",
    initial: "Ge",
    colorClass: "bg-blue-500/10 text-blue-700 dark:text-blue-400",
    borderClass: "border-blue-500/20",
    gradientClass: "from-blue-500/10 to-blue-500/5",
    order: 1,
  },
  {
    providerSlug: "google-deepmind",
    name: "Gemini 3 Flash (Preview)",
    slug: "gemini-3-flash",
    modelId: "gemini-3-flash-preview",
    description: "Fast Gemini 3 model with multimodal capabilities",
    initial: "Ge",
    colorClass: "bg-blue-500/10 text-blue-700 dark:text-blue-400",
    borderClass: "border-blue-500/20",
    gradientClass: "from-blue-500/10 to-blue-500/5",
    order: 2,
  },
  {
    providerSlug: "google-deepmind",
    name: "Gemini 3.1 Flash-Lite (Preview)",
    slug: "gemini-3-flash-lite",
    modelId: "gemini-3.1-flash-lite-preview",
    description: "Lightweight Gemini 3.1 Flash model (preview)",
    initial: "Ge",
    colorClass: "bg-blue-500/10 text-blue-700 dark:text-blue-400",
    borderClass: "border-blue-500/20",
    gradientClass: "from-blue-500/10 to-blue-500/5",
    order: 3,
  },
  // Google DeepMind models — Gemini 2.5 series
  {
    providerSlug: "google-deepmind",
    name: "Gemini 2.5 Pro",
    slug: "gemini-2-5-pro",
    modelId: "gemini-2.5-pro",
    description: "Gemini 2.5 Pro — high capability model",
    initial: "Ge",
    colorClass: "bg-blue-500/10 text-blue-700 dark:text-blue-400",
    borderClass: "border-blue-500/20",
    gradientClass: "from-blue-500/10 to-blue-500/5",
    order: 4,
  },
  {
    providerSlug: "google-deepmind",
    name: "Gemini 2.5 Flash",
    slug: "gemini-2-5-flash",
    modelId: "gemini-2.5-flash",
    description: "Gemini 2.5 Flash — fast and efficient",
    initial: "Ge",
    colorClass: "bg-blue-500/10 text-blue-700 dark:text-blue-400",
    borderClass: "border-blue-500/20",
    gradientClass: "from-blue-500/10 to-blue-500/5",
    order: 5,
  },
  {
    providerSlug: "google-deepmind",
    name: "Gemini 2.5 Flash Lite",
    slug: "gemini-2-5-flash-lite",
    modelId: "gemini-2.5-flash-lite",
    description: "Gemini 2.5 Flash Lite — lightweight and cost-efficient",
    initial: "Ge",
    colorClass: "bg-blue-500/10 text-blue-700 dark:text-blue-400",
    borderClass: "border-blue-500/20",
    gradientClass: "from-blue-500/10 to-blue-500/5",
    order: 6,
  },
  {
    providerSlug: "google-deepmind",
    name: "Gemini 2.5 Flash Image",
    slug: "gemini-2-5-flash-image",
    modelId: "gemini-2.5-flash-image",
    description: "Gemini 2.5 Flash optimised for image understanding",
    initial: "Ge",
    colorClass: "bg-blue-500/10 text-blue-700 dark:text-blue-400",
    borderClass: "border-blue-500/20",
    gradientClass: "from-blue-500/10 to-blue-500/5",
    order: 7,
  },
  // xAI models
  {
    providerSlug: "xai",
    name: "Grok 2",
    slug: "grok-2",
    modelId: "grok-2-latest",
    description: "xAI's flagship conversational model",
    initial: "X",
    colorClass: "bg-zinc-500/10 text-zinc-700 dark:text-zinc-400",
    borderClass: "border-zinc-500/20",
    gradientClass: "from-zinc-500/10 to-zinc-500/5",
    order: 1,
  },
  // Mistral AI models
  {
    providerSlug: "mistral-ai",
    name: "Mistral Large",
    slug: "mistral-large",
    modelId: "mistral-large-latest",
    description: "Mistral's top-tier model for complex tasks",
    initial: "M",
    colorClass: "bg-rose-500/10 text-rose-700 dark:text-rose-400",
    borderClass: "border-rose-500/20",
    gradientClass: "from-rose-500/10 to-rose-500/5",
    order: 1,
  },
  {
    providerSlug: "mistral-ai",
    name: "Mistral Small",
    slug: "mistral-small",
    modelId: "mistral-small-latest",
    description: "Cost-efficient Mistral model",
    initial: "M",
    colorClass: "bg-rose-500/10 text-rose-700 dark:text-rose-400",
    borderClass: "border-rose-500/20",
    gradientClass: "from-rose-500/10 to-rose-500/5",
    order: 2,
  },
  // Together AI models (serving Meta's Llama)
  {
    providerSlug: "together-ai",
    name: "Llama 3.3 70B",
    slug: "llama-3-3-70b",
    modelId: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    description: "Meta's Llama 3.3 70B served via Together AI",
    initial: "L",
    colorClass: "bg-violet-500/10 text-violet-700 dark:text-violet-400",
    borderClass: "border-violet-500/20",
    gradientClass: "from-violet-500/10 to-violet-500/5",
    order: 1,
  },
  {
    providerSlug: "together-ai",
    name: "Llama 3.1 405B",
    slug: "llama-3-1-405b",
    modelId: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
    description: "Meta's most powerful Llama model",
    initial: "L",
    colorClass: "bg-violet-500/10 text-violet-700 dark:text-violet-400",
    borderClass: "border-violet-500/20",
    gradientClass: "from-violet-500/10 to-violet-500/5",
    order: 2,
  },
];

const deprecatedModelSlugs = [
  // Old Gemini models
  "gemini-2-0-flash",
  "gemini-1-5-flash",
  // Old Claude models
  "claude-3-7-sonnet",
  "claude-3-5-haiku",
];

async function main() {
  // Remove deprecated models first
  const deleted = await prisma.aIModel.deleteMany({
    where: { slug: { in: deprecatedModelSlugs } },
  });
  if (deleted.count > 0) {
    console.log(`Deleted ${deleted.count} deprecated model(s): ${deprecatedModelSlugs.join(", ")}`);
  }

  console.log("Seeding AI providers...");

  for (const p of providers) {
    await prisma.aIProvider.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        tier: p.tier,
        website: p.website,
        apiKeyEnv: p.apiKeyEnv,
        apiFormat: p.apiFormat,
        apiBaseUrl: p.apiBaseUrl,
        order: p.order,
      },
      create: {
        name: p.name,
        slug: p.slug,
        tier: p.tier,
        website: p.website ?? null,
        apiKeyEnv: p.apiKeyEnv ?? null,
        apiFormat: p.apiFormat,
        apiBaseUrl: p.apiBaseUrl ?? null,
        order: p.order,
        isActive: true,
      },
    });
  }

  console.log(`Upserted ${providers.length} providers.`);

  console.log("Seeding AI models...");

  for (const m of initialModels) {
    const provider = await prisma.aIProvider.findUnique({ where: { slug: m.providerSlug } });
    if (!provider) {
      console.warn(`Provider not found: ${m.providerSlug}, skipping model ${m.name}`);
      continue;
    }
    await prisma.aIModel.upsert({
      where: { slug: m.slug },
      update: {
        name: m.name,
        modelId: m.modelId,
        description: m.description,
        initial: m.initial,
        colorClass: m.colorClass,
        borderClass: m.borderClass,
        gradientClass: m.gradientClass,
        order: m.order,
      },
      create: {
        providerId: provider.id,
        name: m.name,
        slug: m.slug,
        modelId: m.modelId,
        description: m.description ?? null,
        initial: m.initial,
        colorClass: m.colorClass,
        borderClass: m.borderClass,
        gradientClass: m.gradientClass,
        order: m.order,
        isActive: true,
      },
    });
  }

  console.log(`Upserted ${initialModels.length} models.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
